### ISSUE TITLE
Error migrating datastreams greater than 2 GB in size

### ISSUE THREAD

**Issue by coblej** [projecthydra-labs/fedora-migrate#59]
When the datastream being migrated is greater than 2 GB in size, an exception is thrown during the execution of 'save' in FedoraMigrate::ContentMover#move_content ( https://github.com/projecthydra-labs/fedora-migrate/blob/master/lib/fedora_migrate/content_mover.rb#L28 ).  The stack trace is shown below.  We think that this may be due to the fact that the content of the source datastream is being assigned as a string to the target attached_file content ( https://github.com/projecthydra-labs/fedora-migrate/blob/master/lib/fedora_migrate/content_mover.rb#L25 ) and could perhaps be addressed by wrapping the source content in an IO object.

```
Exception
RangeError
Error
integer 2185175220 too big to convert to `int'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/openssl/buffering.rb:326:in `do_write'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:211:in `write0'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:185:in `block in write'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:202:in `writing'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/protocol.rb:184:in `write'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http/generic_request.rb:184:in `send_request_with_body'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http/generic_request.rb:130:in `exec'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:1412:in `block in transport_request'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:1384:in `request'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:853:in `start'
/home/hydra/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/net/http.rb:1375:in `request'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `put'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/ldp-0.4.1/lib/ldp/client/methods.rb:92:in `block in put'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications.rb:161:in `instrument'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/ldp-0.4.1/lib/ldp/client/methods.rb:90:in `put'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/active-fedora-9.8.2/lib/active_fedora/caching_connection.rb:24:in `put'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/ldp-0.4.1/lib/ldp/resource.rb:72:in `create'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/active-fedora-9.8.2/lib/active_fedora/file.rb:232:in `block (2 levels) in create_record'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/active-fedora-9.8.2/lib/active_fedora/file.rb:229:in `block in create_record'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/active-fedora-9.8.2/lib/active_fedora/file.rb:228:in `create_record'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/active-fedora-9.8.2/lib/active_fedora/persistence.rb:141:in `create_or_update'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/active-fedora-9.8.2/lib/active_fedora/persistence.rb:27:in `save'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/mover.rb:28:in `save'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/content_mover.rb:28:in `move_content'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/content_mover.rb:14:in `migrate'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/datastream_mover.rb:54:in `migrate_content'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/datastream_mover.rb:40:in `migrate_current'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/datastream_mover.rb:34:in `migrate_datastream'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/datastream_mover.rb:23:in `migrate'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/object_mover.rb:59:in `block in migrate_content_datastreams'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/object_mover.rb:57:in `each'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/object_mover.rb:57:in `migrate_content_datastreams'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/object_mover.rb:47:in `migrate_datastreams'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/bundler/gems/fedora-migrate-757504b6443b/lib/fedora_migrate/object_mover.rb:12:in `migrate'
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/migration/migrate_single_object_job.rb:26:in `block in migrate'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/migration/migrate_single_object_job.rb:22:in `migrate'
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/migration/migrate_single_object_job.rb:13:in `block in perform'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/hydra/.rvm/gems/ruby-2.1.8@dul-hydra/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/migration/migrate_single_object_job.rb:10:in `perform'
```

**Comment by jcoyne** [comment]
That looks a lot like this Ruby bug: 
https://bugs.ruby-lang.org/issues/10633

Does it work if you use Ruby 2.1.11?

**Comment by coblej** [comment]
@jcoyne That was our thought as well.  It was our understanding the bug referenced above was fixed beginning in 2.1.6, so we didn't expect to see it in 2.1.8.  We haven't tried it with 2.1.11.

**Comment by dchandekstark** [comment]
@jcoyne FWIW we know that the same code base can save content > 2GB when it's wrapped in a File object.

**Comment by dchandekstark** [comment]
@jcoyne @awead Our testing suggests that wrapping `source.content` with `StringIO.new` takes care of the issue. @coblej
